name: Deploy To EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository에 올린 파일들을 불러오기
#       아래는 파일불러오는 라이브러리(레파지토리에 저장된 코드를 불러옴)
        uses: actions/checkout@v4

      - name: JDK 21버전 설치
#        아래는 jdk 쉽게 설치해주는 라이브러리
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21

      - name: application.yml 파일 만들기
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.yml

      - name: 테스트 및 빌드하기
        run: ./gradlew clean build

      - name: 빌드된 파일 이름 변경하기
        run: mv ./buil/libs/*SNAPSHOT.jar ./project.jar

#        아래는 빌드된 파일을 EC2에 보냄
      - name: SCP로 EC2에 빌드된 파일 전송하기
        uses: appleboy/scp-action@vo0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: project.jar
#          아래는 EC2에 저장경로 지정하는 코드, 바뀔 프로젝트는 toBe 폴더에 넣어놓기
          target: /home/ubuntu/instagram-server/tobe

      - name: SSH(원격 접속)로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
#          원격접속 ip주소
          host: ${{ secrets.EC2_HOST }}
#          ec2 사용자 이름
          username: ${{ secrets.EC2_USERNAME }}
#          ec2 key-pair
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
#            현재 실행중인 서버 프로젝트는 current폴더에 넣어놓기
            rm -rf /home/ubuntu/instagram-server/current
            mkdir /home/ubuntu/instagram-server/current
            mv /home/ubuntu/instagram-server/tobe/project.jar /home/ubuntu/instagram-server/current/project.jar
            cd /home/ubuntu/instagram-server/current
#            실행됐던 서버 끄기
            sudo fuser -k -n tcp 8080 || true
#            jar파일 실행하기
            nohup java -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &
#            기존에 만들었던 tobe 파일 삭제하기
            rm -rf /home/ubuntu/instagram-server/tobe



